export const SUBJECTS = [
  "Agriculture",
  "Ancient History",
  "Biblical Studies",
  "Biology",
  "Business Services",
  "Business Studies",
  "Chemistry",
  "Construction",
  "Drama",
  "Earth and Environmental Science",
  "Economics",
  "Engineering Studies",
  "English Advanced",
  "English EAL/D",
  "English Standard",
  "English Extension",
  "Enterprise Computing",
  "Geography",
  "Industrial Technology - Metal",
  "Industrial Technology - Timber",
  "Junior English",
  "Junior Geography",
  "Junior History",
  "Junior Maths",
  "Junior Science",
  "Languages - Chinese",
  "Languages - French",
  "Languages - German",
  "Legal Studies",
  "Maths Advanced",
  "Maths Extension",
  "Maths Standard",
  "Modern History",
  "Music",
  "PDHPE",
  "Physics",
  "Primary Industries",
  "Software Engineering",
  "Sports, Lifestyle and Recreation",
  "Studies of Religion",
  "Visual Arts",
  "VET / TAFE",
  "Other",
];
